# Generated by Django 3.0.7 on 2020-07-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, null=True)),
                ('code', models.CharField(max_length=8)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cp', models.IntegerField()),
            ],
        ),
    ]
